//! This module provides a validator to detect invalid Weibo images, such as
//! "image deleted" or "image private" placeholders.
//!
//! The [`ImageValidator`] uses a multi-stage heuristic approach:
//! 1.  **Color Sampling**: It checks if pixels at specific locations match the known
//!     gray color range of Weibo's placeholder images.
//! 2.  **Flatness Check**: It calculates the color variance in a small area to see
//!     if the image is unnaturally flat, a characteristic of generated placeholders.
//! 3.  **Perceptual Hashing**: It compares the image's perceptual hash against a
//!     pre-computed set of hashes from known invalid images.
//!
//! An image must pass all stages in sequence to be classified as invalid. This provides
//! a robust defense against false positives. The constants used for these checks
//! are generated at compile time by the `build.rs` script.

use image::{DynamicImage, GenericImageView, Pixel};
use img_hash::{HashAlg, HasherConfig};

// Include constants generated by `build.rs` at compile time.
// These include SAMPLE_GRAY_MIN, SAMPLE_GRAY_MAX, and INVALID_HASHES.
include!(concat!(env!("OUT_DIR"), "/invalid_consts.rs"));

/// Tolerance for differences between R, G, and B channels to account for JPEG compression artifacts.
const RGB_DIFF_TOLERANCE: u8 = 3;
/// A small buffer added to the sampled gray range to increase compatibility.
const RANGE_BUFFER: u8 = 2;
/// The perceptual hash comparison threshold. A Hamming distance below this value is considered a match.
const PHASH_THRESHOLD: u32 = 8;

/// Represents the validation status of an image.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImageStatus {
    /// The image is a standard, valid picture.
    Valid,
    /// The image is a known invalid placeholder (e.g., "deleted" image, gray placeholder).
    Censored,
    /// The image data cannot be parsed (corrupted or not an image format).
    Unparseable,
}

impl ImageStatus {
    /// Returns true if the image should be considered invalid/deleted.
    /// This includes both explicitly invalid placeholders and unparseable images.
    pub fn is_invalid(&self) -> bool {
        matches!(self, ImageStatus::Censored | ImageStatus::Unparseable)
    }
}

/// A validator for detecting invalid Weibo placeholder images.
#[derive(Debug, Clone, Copy)]
pub struct ImageValidator;

impl ImageValidator {
    /// Attempts to decode image data into a DynamicImage.
    ///
    /// # Arguments
    /// * `data` - A byte slice containing the raw image data.
    ///
    /// # Returns
    /// * `Some(img)` - If the image was successfully decoded.
    /// * `None)` - If the image data cannot be parsed as a valid image.
    pub fn decode_image(data: &[u8]) -> Option<DynamicImage> {
        let Ok(reader) = image::io::Reader::new(std::io::Cursor::new(data)).with_guessed_format()
        else {
            return None;
        };

        reader.decode().ok()
    }

    /// Checks if a decoded image is a Weibo gray placeholder (censored).
    ///
    /// This performs the three-stage check:
    /// 1. Color sampling - checks if edge pixels match the gray placeholder color
    /// 2. Flatness check - checks if the image is unnaturally flat (low variance)
    /// 3. Perceptual hash - compares against known invalid image hashes
    ///
    /// # Arguments
    /// * `img` - A decoded DynamicImage.
    ///
    /// # Returns
    /// `true` if the image is a placeholder (censored), `false` otherwise.
    pub fn is_censored(img: &DynamicImage) -> bool {
        let (width, height) = img.dimensions();

        // Small images are not placeholders
        if width < 120 || height < 120 {
            return false;
        }

        // Create hasher for this check
        let hasher = HasherConfig::new()
            .hash_alg(HashAlg::Gradient)
            .hash_size(16, 16)
            .to_hasher();

        // Stage 1: Color Sampling
        if !Self::check_stage1_color(img, width, height) {
            return false;
        }

        // Stage 2: Flatness Check
        if !Self::check_stage2_flatness(img, width, height) {
            return false;
        }

        // Stage 3: Perceptual Hash
        Self::check_stage3_phash(img, &hasher)
    }

    /// Checks if the given image data corresponds to a known invalid Weibo placeholder.
    ///
    /// # Arguments
    /// * `data` - A byte slice containing the raw image data.
    ///
    /// # Returns
    /// A `Result` containing the `ImageStatus`.
    ///
    /// # Errors
    /// Returns `Error::FormatError` if the image data cannot be decoded.
    pub fn is_invalid_weibo_image(data: &[u8]) -> ImageStatus {
        // Try to decode the image first
        let Some(img) = Self::decode_image(data) else {
            return ImageStatus::Unparseable;
        };

        // Check if it's a censored placeholder
        if Self::is_censored(&img) {
            return ImageStatus::Censored;
        }

        ImageStatus::Valid
    }

    /// Stage 1: Checks if edge sample points match the pre-defined "Weibo invalid gray" color.
    fn check_stage1_color(img: &DynamicImage, w: u32, h: u32) -> bool {
        // The boundaries are dynamically determined from samples.
        let min = SAMPLE_GRAY_MIN.saturating_sub(RANGE_BUFFER);
        let max = SAMPLE_GRAY_MAX.saturating_add(RANGE_BUFFER);

        let samples = [
            (w / 10, h / 10),
            (w * 9 / 10, h / 10),
            (w / 10, h * 9 / 10),
            (w * 9 / 10, h * 9 / 10),
            (w / 2, h / 10),
            (w / 2, h * 9 / 10),
        ];

        for (x, y) in samples {
            let rgb = img.get_pixel(x, y).to_rgb().0;

            // Check if R is within the baseline range
            if rgb[0] < min || rgb[0] > max {
                return false;
            }
            // Check if R, G, B are close enough to be considered gray
            let is_gray = (rgb[0] as i16 - rgb[1] as i16).abs() <= RGB_DIFF_TOLERANCE as i16
                && (rgb[1] as i16 - rgb[2] as i16).abs() <= RGB_DIFF_TOLERANCE as i16;

            if !is_gray {
                return false;
            }
        }
        true
    }

    /// Stage 2: Checks background flatness (variance).
    fn check_stage2_flatness(img: &DynamicImage, _w: u32, _h: u32) -> bool {
        let box_size = 32;
        let mut sum = 0.0;
        let mut sum_sq = 0.0;
        let n = (box_size * box_size) as f64;

        for y in 0..box_size {
            for x in 0..box_size {
                let luma = img.get_pixel(x, y).to_luma().0[0] as f64;
                sum += luma;
                sum_sq += luma * luma;
            }
        }

        let mean = sum / n;
        let variance = (sum_sq / n) - (mean * mean);

        // Synthetic images have very low variance; real photos, due to noise, typically have > 0.5.
        variance < 0.2
    }

    /// Stage 3: Perceptual hash comparison.
    fn check_stage3_phash(img: &DynamicImage, hasher: &img_hash::Hasher) -> bool {
        let current_hash = hasher.hash_image(img);

        for base64_hash in INVALID_HASHES {
            if let Ok(target_hash) = img_hash::ImageHash::from_base64(base64_hash)
                && current_hash.dist(&target_hash) <= PHASH_THRESHOLD
            {
                return true;
            }
        }
        false
    }
}
