nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.12.0.cjs
packageExtensions:
  "@mui/x-internals@*":
    peerDependencies:
      react-dom: "*"
    peerDependenciesMeta:
      react-dom:
        optional: true
